export const FETCH_JSONTREE_DATA 					= 'FETCH_JSONTREE_DATA';
export const FETCH_JSONTREE_DATA_SUCCESS 			= 'FETCH_JSONTREE_DATA_SUCCESS';
export const FETCH_JSONTREE_DATA_FAILURE 			= 'FETCH_JSONTREE_DATA_FAILURE';
